device: 'cuda'

# Logging
use_wandb: False
wandb_project: 'osu!-ai'

# Constants
beatmap_path: 'data/formatted_beatmaps/'
vocab_dir: 'preprocessing/vocab/'
model_save_path: 'models/coronation_model.pt'
output_dir: 'output/'
save_model: False # False

# Preprocessing
tokenizer_type: default # sentencepiece
spm_vocab_size: 1000 # Only used if using sentencepiece
relative_timing: True
break_length: 4 # How many beats without a hit object before breaks appear
n_load_workers: 8
include_audio: True

# Model
d_model: 96
d_hid: 1024
n_head: 8
n_encoder_layers: 6
n_decoder_layers: 8

max_src_len: 512
max_tgt_len: 1024
max_gen_len: 1024 # Max length for post-training generation

load_model: True

# Training
lr: 0.0003
epochs: 50
batch_size: 2
dropout: 0
eval_freq: 10000 # In number of samples
val_split: 0.01
test_split: 0.03
max_hit_objects: 80 # Avg ~1400 tokens

# Audio
segments_per_beat: 16 # Determines input to convolution
audio_tokens_per_segment: 2 # Determines convolution size
n_mel_bands: 80
sample_rate: 44100